#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursosVacacionales
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="bdCursosVacacionales")]
	public partial class linqCursosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertALUMNOS(ALUMNOS instance);
    partial void UpdateALUMNOS(ALUMNOS instance);
    partial void DeleteALUMNOS(ALUMNOS instance);
    partial void InsertMATERIAS(MATERIAS instance);
    partial void UpdateMATERIAS(MATERIAS instance);
    partial void DeleteMATERIAS(MATERIAS instance);
    partial void InsertCURSOALUMNOS(CURSOALUMNOS instance);
    partial void UpdateCURSOALUMNOS(CURSOALUMNOS instance);
    partial void DeleteCURSOALUMNOS(CURSOALUMNOS instance);
    partial void InsertCURSOS(CURSOS instance);
    partial void UpdateCURSOS(CURSOS instance);
    partial void DeleteCURSOS(CURSOS instance);
    partial void InsertMAESTROS(MAESTROS instance);
    partial void UpdateMAESTROS(MAESTROS instance);
    partial void DeleteMAESTROS(MAESTROS instance);
    partial void InsertREPORTE(REPORTE instance);
    partial void UpdateREPORTE(REPORTE instance);
    partial void DeleteREPORTE(REPORTE instance);
    #endregion
		
		public linqCursosDataContext() : 
				base(global::CursosVacacionales.Properties.Settings.Default.bdCursosVacacionalesConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public linqCursosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqCursosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqCursosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqCursosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ALUMNOS> ALUMNOS
		{
			get
			{
				return this.GetTable<ALUMNOS>();
			}
		}
		
		public System.Data.Linq.Table<MATERIAS> MATERIAS
		{
			get
			{
				return this.GetTable<MATERIAS>();
			}
		}
		
		public System.Data.Linq.Table<CURSOALUMNOS> CURSOALUMNOS
		{
			get
			{
				return this.GetTable<CURSOALUMNOS>();
			}
		}
		
		public System.Data.Linq.Table<CURSOS> CURSOS
		{
			get
			{
				return this.GetTable<CURSOS>();
			}
		}
		
		public System.Data.Linq.Table<MAESTROS> MAESTROS
		{
			get
			{
				return this.GetTable<MAESTROS>();
			}
		}
		
		public System.Data.Linq.Table<REPORTE> REPORTE
		{
			get
			{
				return this.GetTable<REPORTE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ALUMNOS")]
	public partial class ALUMNOS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _alumno_id;
		
		private string _alumno_nombre;
		
		private decimal _alumno_adeudo;
		
		private EntitySet<CURSOALUMNOS> _CURSOALUMNOS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onalumno_idChanging(string value);
    partial void Onalumno_idChanged();
    partial void Onalumno_nombreChanging(string value);
    partial void Onalumno_nombreChanged();
    partial void Onalumno_adeudoChanging(decimal value);
    partial void Onalumno_adeudoChanged();
    #endregion
		
		public ALUMNOS()
		{
			this._CURSOALUMNOS = new EntitySet<CURSOALUMNOS>(new Action<CURSOALUMNOS>(this.attach_CURSOALUMNOS), new Action<CURSOALUMNOS>(this.detach_CURSOALUMNOS));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alumno_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string alumno_id
		{
			get
			{
				return this._alumno_id;
			}
			set
			{
				if ((this._alumno_id != value))
				{
					this.Onalumno_idChanging(value);
					this.SendPropertyChanging();
					this._alumno_id = value;
					this.SendPropertyChanged("alumno_id");
					this.Onalumno_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alumno_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string alumno_nombre
		{
			get
			{
				return this._alumno_nombre;
			}
			set
			{
				if ((this._alumno_nombre != value))
				{
					this.Onalumno_nombreChanging(value);
					this.SendPropertyChanging();
					this._alumno_nombre = value;
					this.SendPropertyChanged("alumno_nombre");
					this.Onalumno_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alumno_adeudo", DbType="Decimal(18,2) NOT NULL")]
		public decimal alumno_adeudo
		{
			get
			{
				return this._alumno_adeudo;
			}
			set
			{
				if ((this._alumno_adeudo != value))
				{
					this.Onalumno_adeudoChanging(value);
					this.SendPropertyChanging();
					this._alumno_adeudo = value;
					this.SendPropertyChanged("alumno_adeudo");
					this.Onalumno_adeudoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ALUMNOS_CURSOALUMNOS", Storage="_CURSOALUMNOS", ThisKey="alumno_id", OtherKey="alumno_id")]
		public EntitySet<CURSOALUMNOS> CURSOALUMNOS
		{
			get
			{
				return this._CURSOALUMNOS;
			}
			set
			{
				this._CURSOALUMNOS.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CURSOALUMNOS(CURSOALUMNOS entity)
		{
			this.SendPropertyChanging();
			entity.ALUMNOS = this;
		}
		
		private void detach_CURSOALUMNOS(CURSOALUMNOS entity)
		{
			this.SendPropertyChanging();
			entity.ALUMNOS = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MATERIAS")]
	public partial class MATERIAS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _materia_id;
		
		private string _materia_nombre;
		
		private string _materia_semestre;
		
		private EntitySet<CURSOS> _CURSOS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmateria_idChanging(int value);
    partial void Onmateria_idChanged();
    partial void Onmateria_nombreChanging(string value);
    partial void Onmateria_nombreChanged();
    partial void Onmateria_semestreChanging(string value);
    partial void Onmateria_semestreChanged();
    #endregion
		
		public MATERIAS()
		{
			this._CURSOS = new EntitySet<CURSOS>(new Action<CURSOS>(this.attach_CURSOS), new Action<CURSOS>(this.detach_CURSOS));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_materia_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int materia_id
		{
			get
			{
				return this._materia_id;
			}
			set
			{
				if ((this._materia_id != value))
				{
					this.Onmateria_idChanging(value);
					this.SendPropertyChanging();
					this._materia_id = value;
					this.SendPropertyChanged("materia_id");
					this.Onmateria_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_materia_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string materia_nombre
		{
			get
			{
				return this._materia_nombre;
			}
			set
			{
				if ((this._materia_nombre != value))
				{
					this.Onmateria_nombreChanging(value);
					this.SendPropertyChanging();
					this._materia_nombre = value;
					this.SendPropertyChanged("materia_nombre");
					this.Onmateria_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_materia_semestre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string materia_semestre
		{
			get
			{
				return this._materia_semestre;
			}
			set
			{
				if ((this._materia_semestre != value))
				{
					this.Onmateria_semestreChanging(value);
					this.SendPropertyChanging();
					this._materia_semestre = value;
					this.SendPropertyChanged("materia_semestre");
					this.Onmateria_semestreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MATERIAS_CURSOS", Storage="_CURSOS", ThisKey="materia_id", OtherKey="materia_id")]
		public EntitySet<CURSOS> CURSOS
		{
			get
			{
				return this._CURSOS;
			}
			set
			{
				this._CURSOS.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CURSOS(CURSOS entity)
		{
			this.SendPropertyChanging();
			entity.MATERIAS = this;
		}
		
		private void detach_CURSOS(CURSOS entity)
		{
			this.SendPropertyChanging();
			entity.MATERIAS = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CURSOALUMNOS")]
	public partial class CURSOALUMNOS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _curso_id;
		
		private string _alumno_id;
		
		private int _cursoalumno_id;
		
		private EntityRef<ALUMNOS> _ALUMNOS;
		
		private EntityRef<CURSOS> _CURSOS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncurso_idChanging(int value);
    partial void Oncurso_idChanged();
    partial void Onalumno_idChanging(string value);
    partial void Onalumno_idChanged();
    partial void Oncursoalumno_idChanging(int value);
    partial void Oncursoalumno_idChanged();
    #endregion
		
		public CURSOALUMNOS()
		{
			this._ALUMNOS = default(EntityRef<ALUMNOS>);
			this._CURSOS = default(EntityRef<CURSOS>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_curso_id", DbType="Int NOT NULL")]
		public int curso_id
		{
			get
			{
				return this._curso_id;
			}
			set
			{
				if ((this._curso_id != value))
				{
					if (this._CURSOS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncurso_idChanging(value);
					this.SendPropertyChanging();
					this._curso_id = value;
					this.SendPropertyChanged("curso_id");
					this.Oncurso_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alumno_id", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string alumno_id
		{
			get
			{
				return this._alumno_id;
			}
			set
			{
				if ((this._alumno_id != value))
				{
					if (this._ALUMNOS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onalumno_idChanging(value);
					this.SendPropertyChanging();
					this._alumno_id = value;
					this.SendPropertyChanged("alumno_id");
					this.Onalumno_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cursoalumno_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cursoalumno_id
		{
			get
			{
				return this._cursoalumno_id;
			}
			set
			{
				if ((this._cursoalumno_id != value))
				{
					this.Oncursoalumno_idChanging(value);
					this.SendPropertyChanging();
					this._cursoalumno_id = value;
					this.SendPropertyChanged("cursoalumno_id");
					this.Oncursoalumno_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ALUMNOS_CURSOALUMNOS", Storage="_ALUMNOS", ThisKey="alumno_id", OtherKey="alumno_id", IsForeignKey=true)]
		public ALUMNOS ALUMNOS
		{
			get
			{
				return this._ALUMNOS.Entity;
			}
			set
			{
				ALUMNOS previousValue = this._ALUMNOS.Entity;
				if (((previousValue != value) 
							|| (this._ALUMNOS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ALUMNOS.Entity = null;
						previousValue.CURSOALUMNOS.Remove(this);
					}
					this._ALUMNOS.Entity = value;
					if ((value != null))
					{
						value.CURSOALUMNOS.Add(this);
						this._alumno_id = value.alumno_id;
					}
					else
					{
						this._alumno_id = default(string);
					}
					this.SendPropertyChanged("ALUMNOS");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CURSOS_CURSOALUMNOS", Storage="_CURSOS", ThisKey="curso_id", OtherKey="curso_id", IsForeignKey=true)]
		public CURSOS CURSOS
		{
			get
			{
				return this._CURSOS.Entity;
			}
			set
			{
				CURSOS previousValue = this._CURSOS.Entity;
				if (((previousValue != value) 
							|| (this._CURSOS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CURSOS.Entity = null;
						previousValue.CURSOALUMNOS.Remove(this);
					}
					this._CURSOS.Entity = value;
					if ((value != null))
					{
						value.CURSOALUMNOS.Add(this);
						this._curso_id = value.curso_id;
					}
					else
					{
						this._curso_id = default(int);
					}
					this.SendPropertyChanged("CURSOS");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CURSOS")]
	public partial class CURSOS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _curso_id;
		
		private int _materia_id;
		
		private string _maestro_id;
		
		private string _curso_hora;
		
		private string _curso_salon;
		
		private EntitySet<CURSOALUMNOS> _CURSOALUMNOS;
		
		private EntityRef<MATERIAS> _MATERIAS;
		
		private EntityRef<MAESTROS> _MAESTROS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncurso_idChanging(int value);
    partial void Oncurso_idChanged();
    partial void Onmateria_idChanging(int value);
    partial void Onmateria_idChanged();
    partial void Onmaestro_idChanging(string value);
    partial void Onmaestro_idChanged();
    partial void Oncurso_horaChanging(string value);
    partial void Oncurso_horaChanged();
    partial void Oncurso_salonChanging(string value);
    partial void Oncurso_salonChanged();
    #endregion
		
		public CURSOS()
		{
			this._CURSOALUMNOS = new EntitySet<CURSOALUMNOS>(new Action<CURSOALUMNOS>(this.attach_CURSOALUMNOS), new Action<CURSOALUMNOS>(this.detach_CURSOALUMNOS));
			this._MATERIAS = default(EntityRef<MATERIAS>);
			this._MAESTROS = default(EntityRef<MAESTROS>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_curso_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int curso_id
		{
			get
			{
				return this._curso_id;
			}
			set
			{
				if ((this._curso_id != value))
				{
					this.Oncurso_idChanging(value);
					this.SendPropertyChanging();
					this._curso_id = value;
					this.SendPropertyChanged("curso_id");
					this.Oncurso_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_materia_id", DbType="Int NOT NULL")]
		public int materia_id
		{
			get
			{
				return this._materia_id;
			}
			set
			{
				if ((this._materia_id != value))
				{
					if (this._MATERIAS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onmateria_idChanging(value);
					this.SendPropertyChanging();
					this._materia_id = value;
					this.SendPropertyChanged("materia_id");
					this.Onmateria_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maestro_id", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string maestro_id
		{
			get
			{
				return this._maestro_id;
			}
			set
			{
				if ((this._maestro_id != value))
				{
					if (this._MAESTROS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onmaestro_idChanging(value);
					this.SendPropertyChanging();
					this._maestro_id = value;
					this.SendPropertyChanged("maestro_id");
					this.Onmaestro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_curso_hora", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string curso_hora
		{
			get
			{
				return this._curso_hora;
			}
			set
			{
				if ((this._curso_hora != value))
				{
					this.Oncurso_horaChanging(value);
					this.SendPropertyChanging();
					this._curso_hora = value;
					this.SendPropertyChanged("curso_hora");
					this.Oncurso_horaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_curso_salon", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string curso_salon
		{
			get
			{
				return this._curso_salon;
			}
			set
			{
				if ((this._curso_salon != value))
				{
					this.Oncurso_salonChanging(value);
					this.SendPropertyChanging();
					this._curso_salon = value;
					this.SendPropertyChanged("curso_salon");
					this.Oncurso_salonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CURSOS_CURSOALUMNOS", Storage="_CURSOALUMNOS", ThisKey="curso_id", OtherKey="curso_id")]
		public EntitySet<CURSOALUMNOS> CURSOALUMNOS
		{
			get
			{
				return this._CURSOALUMNOS;
			}
			set
			{
				this._CURSOALUMNOS.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MATERIAS_CURSOS", Storage="_MATERIAS", ThisKey="materia_id", OtherKey="materia_id", IsForeignKey=true)]
		public MATERIAS MATERIAS
		{
			get
			{
				return this._MATERIAS.Entity;
			}
			set
			{
				MATERIAS previousValue = this._MATERIAS.Entity;
				if (((previousValue != value) 
							|| (this._MATERIAS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MATERIAS.Entity = null;
						previousValue.CURSOS.Remove(this);
					}
					this._MATERIAS.Entity = value;
					if ((value != null))
					{
						value.CURSOS.Add(this);
						this._materia_id = value.materia_id;
					}
					else
					{
						this._materia_id = default(int);
					}
					this.SendPropertyChanged("MATERIAS");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAESTROS_CURSOS", Storage="_MAESTROS", ThisKey="maestro_id", OtherKey="maestro_id", IsForeignKey=true)]
		public MAESTROS MAESTROS
		{
			get
			{
				return this._MAESTROS.Entity;
			}
			set
			{
				MAESTROS previousValue = this._MAESTROS.Entity;
				if (((previousValue != value) 
							|| (this._MAESTROS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MAESTROS.Entity = null;
						previousValue.CURSOS.Remove(this);
					}
					this._MAESTROS.Entity = value;
					if ((value != null))
					{
						value.CURSOS.Add(this);
						this._maestro_id = value.maestro_id;
					}
					else
					{
						this._maestro_id = default(string);
					}
					this.SendPropertyChanged("MAESTROS");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CURSOALUMNOS(CURSOALUMNOS entity)
		{
			this.SendPropertyChanging();
			entity.CURSOS = this;
		}
		
		private void detach_CURSOALUMNOS(CURSOALUMNOS entity)
		{
			this.SendPropertyChanging();
			entity.CURSOS = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAESTROS")]
	public partial class MAESTROS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maestro_id;
		
		private string _maestro_nombre;
		
		private decimal _maestro_sueldo;
		
		private EntitySet<CURSOS> _CURSOS;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmaestro_idChanging(string value);
    partial void Onmaestro_idChanged();
    partial void Onmaestro_nombreChanging(string value);
    partial void Onmaestro_nombreChanged();
    partial void Onmaestro_sueldoChanging(decimal value);
    partial void Onmaestro_sueldoChanged();
    #endregion
		
		public MAESTROS()
		{
			this._CURSOS = new EntitySet<CURSOS>(new Action<CURSOS>(this.attach_CURSOS), new Action<CURSOS>(this.detach_CURSOS));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maestro_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maestro_id
		{
			get
			{
				return this._maestro_id;
			}
			set
			{
				if ((this._maestro_id != value))
				{
					this.Onmaestro_idChanging(value);
					this.SendPropertyChanging();
					this._maestro_id = value;
					this.SendPropertyChanged("maestro_id");
					this.Onmaestro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maestro_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string maestro_nombre
		{
			get
			{
				return this._maestro_nombre;
			}
			set
			{
				if ((this._maestro_nombre != value))
				{
					this.Onmaestro_nombreChanging(value);
					this.SendPropertyChanging();
					this._maestro_nombre = value;
					this.SendPropertyChanged("maestro_nombre");
					this.Onmaestro_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maestro_sueldo", DbType="Decimal(18,2) NOT NULL")]
		public decimal maestro_sueldo
		{
			get
			{
				return this._maestro_sueldo;
			}
			set
			{
				if ((this._maestro_sueldo != value))
				{
					this.Onmaestro_sueldoChanging(value);
					this.SendPropertyChanging();
					this._maestro_sueldo = value;
					this.SendPropertyChanged("maestro_sueldo");
					this.Onmaestro_sueldoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAESTROS_CURSOS", Storage="_CURSOS", ThisKey="maestro_id", OtherKey="maestro_id")]
		public EntitySet<CURSOS> CURSOS
		{
			get
			{
				return this._CURSOS;
			}
			set
			{
				this._CURSOS.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CURSOS(CURSOS entity)
		{
			this.SendPropertyChanging();
			entity.MAESTROS = this;
		}
		
		private void detach_CURSOS(CURSOS entity)
		{
			this.SendPropertyChanging();
			entity.MAESTROS = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class REPORTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _curso_id;
		
		private string _materia_nombre;
		
		private string _curso_hora;
		
		private string _curso_salon;
		
		private string _maestro_nombre;
		
		private string _alumno_id;
		
		private string _alumno_nombre;
		
		private decimal _alumno_adeudo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncurso_idChanging(int value);
    partial void Oncurso_idChanged();
    partial void Onmateria_nombreChanging(string value);
    partial void Onmateria_nombreChanged();
    partial void Oncurso_horaChanging(string value);
    partial void Oncurso_horaChanged();
    partial void Oncurso_salonChanging(string value);
    partial void Oncurso_salonChanged();
    partial void Onmaestro_nombreChanging(string value);
    partial void Onmaestro_nombreChanged();
    partial void Onalumno_idChanging(string value);
    partial void Onalumno_idChanged();
    partial void Onalumno_nombreChanging(string value);
    partial void Onalumno_nombreChanged();
    partial void Onalumno_adeudoChanging(decimal value);
    partial void Onalumno_adeudoChanged();
    #endregion
		
		public REPORTE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_curso_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int curso_id
		{
			get
			{
				return this._curso_id;
			}
			set
			{
				if ((this._curso_id != value))
				{
					this.Oncurso_idChanging(value);
					this.SendPropertyChanging();
					this._curso_id = value;
					this.SendPropertyChanged("curso_id");
					this.Oncurso_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_materia_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string materia_nombre
		{
			get
			{
				return this._materia_nombre;
			}
			set
			{
				if ((this._materia_nombre != value))
				{
					this.Onmateria_nombreChanging(value);
					this.SendPropertyChanging();
					this._materia_nombre = value;
					this.SendPropertyChanged("materia_nombre");
					this.Onmateria_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_curso_hora", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string curso_hora
		{
			get
			{
				return this._curso_hora;
			}
			set
			{
				if ((this._curso_hora != value))
				{
					this.Oncurso_horaChanging(value);
					this.SendPropertyChanging();
					this._curso_hora = value;
					this.SendPropertyChanged("curso_hora");
					this.Oncurso_horaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_curso_salon", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string curso_salon
		{
			get
			{
				return this._curso_salon;
			}
			set
			{
				if ((this._curso_salon != value))
				{
					this.Oncurso_salonChanging(value);
					this.SendPropertyChanging();
					this._curso_salon = value;
					this.SendPropertyChanged("curso_salon");
					this.Oncurso_salonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maestro_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string maestro_nombre
		{
			get
			{
				return this._maestro_nombre;
			}
			set
			{
				if ((this._maestro_nombre != value))
				{
					this.Onmaestro_nombreChanging(value);
					this.SendPropertyChanging();
					this._maestro_nombre = value;
					this.SendPropertyChanged("maestro_nombre");
					this.Onmaestro_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alumno_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string alumno_id
		{
			get
			{
				return this._alumno_id;
			}
			set
			{
				if ((this._alumno_id != value))
				{
					this.Onalumno_idChanging(value);
					this.SendPropertyChanging();
					this._alumno_id = value;
					this.SendPropertyChanged("alumno_id");
					this.Onalumno_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alumno_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string alumno_nombre
		{
			get
			{
				return this._alumno_nombre;
			}
			set
			{
				if ((this._alumno_nombre != value))
				{
					this.Onalumno_nombreChanging(value);
					this.SendPropertyChanging();
					this._alumno_nombre = value;
					this.SendPropertyChanged("alumno_nombre");
					this.Onalumno_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alumno_adeudo", DbType="Decimal(18,2) NOT NULL")]
		public decimal alumno_adeudo
		{
			get
			{
				return this._alumno_adeudo;
			}
			set
			{
				if ((this._alumno_adeudo != value))
				{
					this.Onalumno_adeudoChanging(value);
					this.SendPropertyChanging();
					this._alumno_adeudo = value;
					this.SendPropertyChanged("alumno_adeudo");
					this.Onalumno_adeudoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
